export const STRINGS = Object.freeze({
  avatarLabel: 'Scamerinio',
  avatarTitle: 'Kliknij mnie, a sprawdzimy wiadomość razem.',
  hideLabel: 'Schowaj pomocnika',
  hideTitle: 'Schowam się. Wrócę, gdy odświeżysz stronę albo klikniesz moją ikonę na pasku przeglądarki.',
  panelLabel: 'Scamerinio', closeLabel: 'Zamknij okno', closeSymbol: '×',
  menuIntro: 'Cześć! W czym pomóc?', menuCheck: 'Sprawdź wiadomość', menuHowTo: 'Jak to działa',
  pasteHeading: 'Wklej wiadomość', messageLabel: 'Wiadomość', pastePlaceholder: 'Wklej tutaj tekst wiadomości',
  linkLabel: 'Link (jeśli jest)', linkPlaceholder: 'np. https://…', next: 'Dalej', back: 'Wróć',
  emptyHint: 'Najpierw wklej albo wpisz wiadomość.',
  previewHeading: 'Sprawdź, co mi pokazujesz',
  previewHint: 'Możesz poprawić tekst, na przykład usunąć swoje imię albo inne dane.',
  sourcePrefix: 'Ze strony:',
  guardianNotice: 'Gdy zatwierdzisz, tę wiadomość i wynik sprawdzania zobaczy Twój opiekun.',
  approve: 'Zatwierdzam',
  newSelectionHint: 'Na stronie jest nowe zaznaczenie. Możesz je wstawić zamiast tej wiadomości.',
  insertNewSelection: 'Wstaw nowe zaznaczenie',
  truncatedNotice: 'Wiadomość była bardzo długa, więc biorę tylko jej początek (2000 znaków).',
  confirmationHeading: 'Przekazano opiekunowi — demo',
  confirmationBody: 'To pokaz działania. Sprawa i wynik są zapisane tylko w pamięci rozszerzenia. Prawdziwa wysyłka do opiekuna będzie dostępna w fazie 3.',
  confirmationClose: 'Zamknij',
  requestGuardianVerification: 'Poproś opiekuna o sprawdzenie',
  guardianRequestError: 'Nie udało się zapisać prośby w pokazie. Spróbuj jeszcze raz.',
  safetyNotice: 'Zanim sprawdzimy: nie podawaj hasła ani kodu i nie klikaj nieznanego linku.',
  hintBadge: 'Podpowiedź z wiadomości',
  fixAnswers: 'Popraw odpowiedzi',
  editCheckContent: 'Edytuj wiadomość',
  cancelCheckEdit: 'Wróć do sprawdzania',
  checkNewSelection: 'Sprawdź nowe zaznaczenie',
  correctAnswer: 'Popraw odpowiedź',
  keepAnswer: 'Zostaw moją odpowiedź',
  checkMismatches: Object.freeze({
    credential_code: 'W wiadomości jest prośba o kod. Czy chcesz zmienić odpowiedź?',
    credential_password: 'W wiadomości jest prośba o hasło. Czy chcesz zmienić odpowiedź?',
  }),
  checkQuestions: Object.freeze([
    Object.freeze({ id: 'sender', title: 'Kto wysłał wiadomość?', multiple: false, options: Object.freeze([
      { id: 'known_person', label: 'Osoba, którą znam' },
      { id: 'claims_organization', label: 'Ktoś podaje się za firmę lub organizację' },
      { id: 'unknown_sender', label: 'Nie znam nadawcy' },
      { id: 'unknown', label: 'Nie wiem' },
    ]) }),
    Object.freeze({ id: 'request', title: 'Czego chce nadawca i czy pogania?', multiple: true, options: Object.freeze([
      { id: 'password', label: 'Podania hasła' },
      { id: 'code', label: 'Podania kodu do konta' },
      { id: 'prize', label: 'Odebrania darmowej nagrody' },
      { id: 'payment', label: 'Zapłaty lub przelewu' },
      { id: 'urgency', label: 'Szybkiego działania, bez czasu na sprawdzenie' },
      { id: 'ordinary', label: 'Zwykła wiadomość, bez takich próśb' },
      { id: 'unknown', label: 'Nie wiem' },
    ]) }),
    Object.freeze({ id: 'verify', title: 'Jak możesz sprawdzić poza tą wiadomością?', multiple: false, options: Object.freeze([
      { id: 'independent_channel', label: 'Przez znaną mi aplikację, stronę lub kontakt' },
      { id: 'message_link', label: 'Tylko przez link z tej wiadomości' },
      { id: 'no_channel', label: 'Nie mam innego sposobu' },
      { id: 'unknown', label: 'Nie wiem' },
    ]) }),
  ]),
  resultSections: Object.freeze({ signals: 'Co zwraca uwagę', unknowns: 'Czego jeszcze nie wiemy', step: 'Co możesz teraz zrobić' }),
  checkSummaries: Object.freeze({
    no_signal: 'Nie widzę typowych sygnałów oszustwa. To nie daje pewności — sprawdź wiadomość oficjalnym kanałem.',
    no_signals: 'Nie widzę typowych sygnałów oszustwa. To nie daje pewności — sprawdź wiadomość oficjalnym kanałem.',
    missing_information: 'Brakuje nam informacji. Możesz spokojnie sprawdzić wiadomość przez znany Ci kontakt.',
    insufficient_information: 'Brakuje nam informacji. Możesz spokojnie sprawdzić wiadomość przez znany Ci kontakt.',
    caution: 'Ta wiadomość wymaga ostrożności. Sprawdź, co zwraca uwagę, zanim zrobisz kolejny krok.',
    conflicting_answers: 'Twoja odpowiedź różni się od prośby rozpoznanej w wiadomości. Nie mamy pewności, jak ją rozumieć; ostrzeżenie o haśle lub kodzie pozostaje.',
  }),
  checkSignals: Object.freeze({
    none: 'Nie widzę typowych sygnałów oszustwa w wiadomości ani w Twoich odpowiedziach.',
    password: 'Prośba o hasło to sygnał ostrzegawczy. Nie podawaj go.',
    code: 'Prośba o kod do konta to sygnał ostrzegawczy. Nie podawaj go.',
    credential_password: 'Prośba o hasło to sygnał ostrzegawczy. Nie podawaj go.',
    credential_code: 'Prośba o kod do konta to sygnał ostrzegawczy. Nie podawaj go.',
    payment: 'Prośba o zapłatę wymaga sprawdzenia poza wiadomością.',
    payment_pressure: 'Prośba o zapłatę wymaga sprawdzenia poza wiadomością. Pośpiech lub groźba straty utrudnia spokojną decyzję.',
    prize_link: 'Wiadomość zachęca do odebrania darmowej nagrody przez podany link. Sprawdź tę ofertę poza wiadomością.',
    urgency: 'Pośpiech utrudnia sprawdzenie wiadomości. Możesz się zatrzymać.',
    prize: 'Darmową nagrodę warto sprawdzić w znanej Ci oficjalnej aplikacji lub stronie.',
  }),
  checkUnknowns: Object.freeze({
    none: 'Nie wskazano dodatkowych brakujących informacji. To nie potwierdza tożsamości nadawcy ani bezpieczeństwa wiadomości.',
    sender: 'Nie wiemy jeszcze, kto naprawdę wysłał wiadomość.',
    request: 'Nie wiemy jeszcze, czego nadawca oczekuje.',
    verify: 'Nie wiemy jeszcze, jak sprawdzić wiadomość niezależnie.',
    official_channel: 'Nie wiemy jeszcze, jak sprawdzić wiadomość niezależnie.',
    urgency: 'Nie wiemy jeszcze, czy nadawca pogania i ile masz czasu na sprawdzenie.',
    conflict: 'Nie wiemy, jak rozumieć różnicę między Twoją odpowiedzią a prośbą w wiadomości. Nie podawaj hasła ani kodu, zanim sprawdzisz ją niezależnie.',
  }),
  checkSteps: Object.freeze({
    independent_check: 'Sprawdź przez znany Ci kanał',
    independent_check_how: 'Otwórz znaną Ci oficjalną aplikację lub stronę bezpośrednio albo skontaktuj się z nadawcą przez wcześniej znany kontakt.',
    do_not_share: 'Zatrzymaj się i nie podawaj hasła ani kodu',
    do_not_share_how: 'Nie odpowiadaj hasłem ani kodem. Otwórz znaną Ci aplikację bezpośrednio lub poproś zaufaną osobę o pomoc w sprawdzeniu.',
    protect_credentials: 'Zatrzymaj się i nie podawaj hasła ani kodu',
    protect_credentials_how: 'Nie odpowiadaj hasłem ani kodem. Poproś zaufaną osobę dorosłą o pomoc lub skontaktuj się z pomocą przez znaną Ci oficjalną aplikację albo stronę, otwartą bez linku z wiadomości.',
    verify_payment: 'Sprawdź prośbę, zanim zapłacisz',
    verify_payment_how: 'Skontaktuj się z nadawcą przez wcześniej znany kontakt. Możesz poprosić zaufaną osobę o pomoc, zanim przekażesz pieniądze.',
    verify_prize: 'Sprawdź nagrodę poza wiadomością',
    verify_prize_how: 'Otwórz znaną Ci oficjalną aplikację lub stronę samodzielnie, bez podanego linku. Sprawdź, czy taka nagroda jest tam opisana, lub poproś zaufaną osobę dorosłą o pomoc.',
    pause_and_verify: 'Zatrzymaj się i sprawdź bez pośpiechu',
    pause_and_verify_how: 'Zrób przerwę. Skontaktuj się z nadawcą przez wcześniej znany kontakt albo otwórz znaną Ci oficjalną aplikację bez linku z wiadomości. Możesz poprosić zaufaną osobę dorosłą o pomoc.',
  }),
  submitError: 'Coś poszło nie tak. Odśwież stronę i spróbuj jeszcze raz.',
  howToHeading: 'Jak to działa',
  howToSteps: ['Zaznacz wiadomość, którą chcesz sprawdzić.', 'Kliknij mnie.', 'Sprawdź tekst i zatwierdź.'],
  howToPrivacy: 'Widzę tylko to, co mi pokażesz. Zatwierdzoną sprawę zobaczy Twój opiekun.',
});
