export const STRINGS = Object.freeze({
  avatarLabel: 'Scamerinio',
  avatarTitle: 'Kliknij mnie, a sprawdzimy wiadomość razem.',
  hideLabel: 'Schowaj pomocnika',
  hideTitle: 'Schowam się. Wrócę, gdy odświeżysz stronę albo klikniesz moją ikonę na pasku przeglądarki.',
  panelLabel: 'Scamerinio', closeLabel: 'Zamknij okno', closeSymbol: '×',
  menuIntro: 'Cześć! W czym pomóc?', menuCheck: 'Sprawdź wiadomość', menuHowTo: 'Jak to działa',
  pasteHeading: 'Wklej wiadomość', messageLabel: 'Wiadomość', pastePlaceholder: 'Wklej tutaj tekst wiadomości',
  linkLabel: 'Link (jeśli jest)', linkPlaceholder: 'np. https://…', next: 'Dalej', back: 'Wróć',
  emptyHint: 'Najpierw wklej albo wpisz wiadomość.',
  previewHeading: 'Sprawdź, co mi pokazujesz',
  previewHint: 'Możesz poprawić tekst, na przykład usunąć swoje imię albo inne dane.',
  sourcePrefix: 'Ze strony:',
  guardianNotice: 'Gdy zatwierdzisz, tę wiadomość i wynik sprawdzania zobaczy Twój opiekun.',
  approve: 'Zatwierdzam',
  newSelectionHint: 'Na stronie jest nowe zaznaczenie. Możesz je wstawić zamiast tej wiadomości.',
  insertNewSelection: 'Wstaw nowe zaznaczenie',
  truncatedNotice: 'Wiadomość była bardzo długa, więc biorę tylko jej początek (2000 znaków).',
  confirmationHeading: 'Gotowe!', confirmationBody: 'Sprawa jest przygotowana do sprawdzenia.', confirmationClose: 'Zamknij',
  submitError: 'Coś poszło nie tak. Odśwież stronę i spróbuj jeszcze raz.',
  howToHeading: 'Jak to działa',
  howToSteps: ['Zaznacz wiadomość, którą chcesz sprawdzić.', 'Kliknij mnie.', 'Sprawdź tekst i zatwierdź.'],
  howToPrivacy: 'Widzę tylko to, co mi pokażesz. Zatwierdzoną sprawę zobaczy Twój opiekun.',
});
