export const STRINGS = Object.freeze({
  avatarLabel: 'Scamerinio',
  avatarTitle: 'Kliknij mnie, a sprawdzimy wiadomość razem.',
  hideLabel: 'Schowaj pomocnika',
  hideTitle: 'Schowam się. Wrócę, gdy odświeżysz stronę albo klikniesz moją ikonę na pasku przeglądarki.',
  panelLabel: 'Scamerinio', closeLabel: 'Zamknij okno', closeSymbol: '×',
  menuIntro: 'Cześć! W czym pomóc?', menuCheck: 'Sprawdź wiadomość', menuReports: 'Moje zgłoszenia', menuHowTo: 'Jak to działa',
  pasteHeading: 'Wklej wiadomość', messageLabel: 'Wiadomość', pastePlaceholder: 'Wklej tutaj tekst wiadomości',
  linkLabel: 'Link (jeśli jest)', linkPlaceholder: 'np. https://…', next: 'Dalej', back: 'Wróć',
  emptyHint: 'Najpierw wklej albo wpisz wiadomość.',
  previewHeading: 'Sprawdź, co mi pokazujesz',
  previewHint: 'Możesz poprawić tekst, na przykład usunąć swoje imię albo inne dane.',
  sourcePrefix: 'Ze strony:',
  guardianNotice: 'Najpierw razem sprawdzimy wiadomość. Nic nie wysyłam, dopóki sam nie wybierzesz „Pokaż opiekunowi” i „Wyślij”.',
  approve: 'Zatwierdzam',
  newSelectionHint: 'Na stronie jest nowe zaznaczenie. Możesz je wstawić zamiast tej wiadomości.',
  insertNewSelection: 'Wstaw nowe zaznaczenie',
  truncatedNotice: 'Wiadomość była bardzo długa, więc biorę tylko jej początek (2000 znaków).',
  showSendPreview: 'Pokaż opiekunowi',
  sendPreviewHeading: 'Sprawdź, co wyślesz',
  recipientPrefix: 'Do:',
  reportContentLabel: 'Treść zgłoszenia',
  sendEditHint: 'Chcesz coś usunąć z treści? Wróć do wyniku i wybierz „Edytuj wiadomość”.',
  attackLegend: 'Na co to wygląda?',
  proposalBadge: 'Propozycja z Twoich odpowiedzi',
  actionsLegend: 'Co już zrobiłeś?',
  actionsHint: 'Zaznacz tylko to, co się stało. Jeśli nic z tego, nie zaznaczaj niczego.',
  noActions: 'Nic z tych rzeczy',
  reportSourceLabel: 'Skąd jest ta wiadomość?',
  sendPrivacy: 'Zobaczy to Twój rodzic. Wynik sprawdzania i Twoje odpowiedzi nie są wysyłane.',
  send: 'Wyślij', sending: 'Wysyłam…', sendRetry: 'Spróbuj ponownie', sendAgain: 'Wyślij jeszcze raz',
  noAccount: 'Wtyczka nie jest połączona z kontem rodzica. Poproś rodzica o zalogowanie.',
  openLogin: 'Otwórz logowanie',
  sentRecipientPrefix: 'Wysłano do:',
  sentTimePrefix: 'Godzina wysłania:',
  sentStatus: 'Status: Czeka, aż rodzic zobaczy',
  sentHint: 'Co dalej, sprawdzisz w menu: „Moje zgłoszenia”.',
  confirmationClose: 'Zamknij',
  checkNewMessage: 'Sprawdź nową wiadomość',
  myReports: 'Moje zgłoszenia',
  // HND-03 / D-14: status is the parent's answer. Calm child labels, no judgement, one colour.
  reportsIntro: 'Ostatnie zgłoszenia i to, co dzieje się z nimi teraz.',
  reportsLoading: 'Wczytuję zgłoszenia…',
  reportsEmptyTitle: 'Nie ma jeszcze zgłoszeń',
  reportsEmptyBody: 'Gdy pokażesz coś opiekunowi, zobaczysz tutaj, co się z tym dzieje.',
  reportsErrorTitle: 'Nie udało się wczytać zgłoszeń',
  reportsErrorBody: 'Sprawdź internet i spróbuj ponownie.',
  reportsRetry: 'Spróbuj ponownie',
  reportStates: Object.freeze({
    pending_parent: 'Czeka, aż rodzic zobaczy',
    with_teacher: 'Rodzic poprosił o pomoc nauczyciela',
    escalated: 'Dorośli zgłosili to dalej',
    closed: 'Sprawa zamknięta',
    rejected: 'Rodzic zobaczył — porozmawiajcie o tym',
  }),
  // HND-02 / D-15: fixed local guidance; it never sends anything. Destinations mirror the
  // canonical web-app DIALOG.escalateWhere list (projects/web-app/src/app/_panel/content.ts).
  platformHowTo: 'Jak zgłosić na platformie',
  platformHeading: 'Jak zgłosić na platformie',
  platformNotice: 'To zgłoszenie do serwisu, nie do rodzica. Ta instrukcja niczego nie wysyła.',
  platformSteps: Object.freeze({
    discord: Object.freeze(['Kliknij wiadomość prawym przyciskiem myszy.', 'Wybierz „Zgłoś wiadomość” i wskaż powód.', 'Możesz też zablokować nadawcę.']),
    game: Object.freeze(['Otwórz menu gry (w Roblox: ikona w lewym górnym rogu).', 'Wybierz „Zgłoś” i wskaż gracza.', 'Krótko opisz, co się stało, i zablokuj gracza.']),
    email: Object.freeze(['Nie klikaj linków ani załączników.', 'Wybierz w poczcie „Zgłoś phishing” albo „Oznacz jako spam”.', 'Usuń wiadomość.']),
    sms: Object.freeze(['Nie odpisuj i nie klikaj linku.', 'Prześlij tego SMS-a na numer 8080 — trafi do CERT Polska. To nic nie kosztuje.', 'Usuń wiadomość.']),
    other: Object.freeze(['Poszukaj przycisku „Zgłoś” przy wiadomości albo profilu nadawcy.', 'Zablokuj nadawcę, jeśli możesz.', 'Oszustwo możesz też zgłosić do CERT Polska.']),
  }),
  platformRoblox: Object.freeze({ text: 'Jak zgłaszać w Roblox', href: 'https://about.roblox.com/reporting-and-blocking' }),
  platformElsewhere: 'Gdzie jeszcze',
  platformLinks: Object.freeze([
    Object.freeze({ text: 'CERT Polska', href: 'https://incydent.cert.pl/', use: 'oszustwa, fałszywe strony i linki' }),
    Object.freeze({ text: 'Dyżurnet.pl', href: 'https://dyzurnet.pl/formularz-zgloszeniowy', use: 'treści, które Cię straszą lub krępują' }),
  ]),
  platformSafety: 'Gdy ktoś Ci grozi albo czujesz się w niebezpieczeństwie, powiedz o tym dorosłemu lub dzwoń pod 112.',
  platformBack: 'Wróć do wyniku',
  sendOutcomes: Object.freeze({
    offline: Object.freeze({ title: 'Nie wysłano — brak połączenia', body: 'Sprawdź internet i spróbuj ponownie. Twoja wiadomość czeka tutaj.' }),
    http: Object.freeze({ title: 'Nie wysłano', body: 'Nie udało się zapisać zgłoszenia. Spróbuj ponownie. Jeśli to się powtórzy, pokaż tę wiadomość rodzicowi na swoim ekranie.' }),
    unknown: Object.freeze({ title: 'Nie wiemy, czy dotarło', body: 'Połączenie przerwało się w trakcie wysyłania. Zanim wyślesz jeszcze raz, otwórz „Moje zgłoszenia” i sprawdź, czy ta wiadomość już tam jest.' }),
    context: Object.freeze({ title: 'Nie wysłano', body: 'Rozszerzenie zostało przeładowane. Odśwież tę stronę i spróbuj jeszcze raz.' }),
  }),
  safetyNotice: 'Zanim sprawdzimy: nie podawaj hasła ani kodu i nie klikaj nieznanego linku.',
  hintBadge: 'Podpowiedź z wiadomości',
  fixAnswers: 'Popraw odpowiedzi',
  editCheckContent: 'Edytuj wiadomość',
  cancelCheckEdit: 'Wróć do sprawdzania',
  checkNewSelection: 'Sprawdź nowe zaznaczenie',
  correctAnswer: 'Popraw odpowiedź',
  keepAnswer: 'Zostaw moją odpowiedź',
  checkMismatches: Object.freeze({
    credential_code: 'W wiadomości jest prośba o kod. Czy chcesz zmienić odpowiedź?',
    credential_password: 'W wiadomości jest prośba o hasło. Czy chcesz zmienić odpowiedź?',
  }),
  checkQuestions: Object.freeze([
    Object.freeze({ id: 'sender', title: 'Kto wysłał wiadomość?', multiple: false, options: Object.freeze([
      { id: 'known_person', label: 'Osoba, którą znam' },
      { id: 'claims_organization', label: 'Ktoś podaje się za firmę lub organizację' },
      { id: 'unknown_sender', label: 'Nie znam nadawcy' },
      { id: 'unknown', label: 'Nie wiem' },
    ]) }),
    Object.freeze({ id: 'request', title: 'Czego chce nadawca i czy pogania?', multiple: true, options: Object.freeze([
      { id: 'password', label: 'Podania hasła' },
      { id: 'code', label: 'Podania kodu do konta' },
      { id: 'prize', label: 'Odebrania darmowej nagrody' },
      { id: 'payment', label: 'Zapłaty lub przelewu' },
      { id: 'urgency', label: 'Szybkiego działania, bez czasu na sprawdzenie' },
      { id: 'ordinary', label: 'Zwykła wiadomość, bez takich próśb' },
      { id: 'unknown', label: 'Nie wiem' },
    ]) }),
    Object.freeze({ id: 'verify', title: 'Jak możesz sprawdzić poza tą wiadomością?', multiple: false, options: Object.freeze([
      { id: 'independent_channel', label: 'Przez znaną mi aplikację, stronę lub kontakt' },
      { id: 'message_link', label: 'Tylko przez link z tej wiadomości' },
      { id: 'no_channel', label: 'Nie mam innego sposobu' },
      { id: 'unknown', label: 'Nie wiem' },
    ]) }),
  ]),
  resultSections: Object.freeze({ signals: 'Co zwraca uwagę', unknowns: 'Czego jeszcze nie wiemy', step: 'Co możesz teraz zrobić' }),
  checkSummaries: Object.freeze({
    no_signal: 'Nie widzę typowych sygnałów oszustwa. To nie daje pewności — sprawdź wiadomość oficjalnym kanałem.',
    no_signals: 'Nie widzę typowych sygnałów oszustwa. To nie daje pewności — sprawdź wiadomość oficjalnym kanałem.',
    missing_information: 'Brakuje nam informacji. Możesz spokojnie sprawdzić wiadomość przez znany Ci kontakt.',
    insufficient_information: 'Brakuje nam informacji. Możesz spokojnie sprawdzić wiadomość przez znany Ci kontakt.',
    caution: 'Ta wiadomość wymaga ostrożności. Sprawdź, co zwraca uwagę, zanim zrobisz kolejny krok.',
    conflicting_answers: 'Twoja odpowiedź różni się od prośby rozpoznanej w wiadomości. Nie mamy pewności, jak ją rozumieć; ostrzeżenie o haśle lub kodzie pozostaje.',
  }),
  checkSignals: Object.freeze({
    none: 'Nie widzę typowych sygnałów oszustwa w wiadomości ani w Twoich odpowiedziach.',
    password: 'Prośba o hasło to sygnał ostrzegawczy. Nie podawaj go.',
    code: 'Prośba o kod do konta to sygnał ostrzegawczy. Nie podawaj go.',
    credential_password: 'Prośba o hasło to sygnał ostrzegawczy. Nie podawaj go.',
    credential_code: 'Prośba o kod do konta to sygnał ostrzegawczy. Nie podawaj go.',
    payment: 'Prośba o zapłatę wymaga sprawdzenia poza wiadomością.',
    payment_pressure: 'Prośba o zapłatę wymaga sprawdzenia poza wiadomością. Pośpiech lub groźba straty utrudnia spokojną decyzję.',
    prize_link: 'Wiadomość zachęca do odebrania darmowej nagrody przez podany link. Sprawdź tę ofertę poza wiadomością.',
    urgency: 'Pośpiech utrudnia sprawdzenie wiadomości. Możesz się zatrzymać.',
    prize: 'Darmową nagrodę warto sprawdzić w znanej Ci oficjalnej aplikacji lub stronie.',
  }),
  checkUnknowns: Object.freeze({
    none: 'Nie wskazano dodatkowych brakujących informacji. To nie potwierdza tożsamości nadawcy ani bezpieczeństwa wiadomości.',
    sender: 'Nie wiemy jeszcze, kto naprawdę wysłał wiadomość.',
    request: 'Nie wiemy jeszcze, czego nadawca oczekuje.',
    verify: 'Nie wiemy jeszcze, jak sprawdzić wiadomość niezależnie.',
    official_channel: 'Nie wiemy jeszcze, jak sprawdzić wiadomość niezależnie.',
    urgency: 'Nie wiemy jeszcze, czy nadawca pogania i ile masz czasu na sprawdzenie.',
    conflict: 'Nie wiemy, jak rozumieć różnicę między Twoją odpowiedzią a prośbą w wiadomości. Nie podawaj hasła ani kodu, zanim sprawdzisz ją niezależnie.',
  }),
  checkSteps: Object.freeze({
    independent_check: 'Sprawdź przez znany Ci kanał',
    independent_check_how: 'Otwórz znaną Ci oficjalną aplikację lub stronę bezpośrednio albo skontaktuj się z nadawcą przez wcześniej znany kontakt.',
    do_not_share: 'Zatrzymaj się i nie podawaj hasła ani kodu',
    do_not_share_how: 'Nie odpowiadaj hasłem ani kodem. Otwórz znaną Ci aplikację bezpośrednio lub poproś zaufaną osobę o pomoc w sprawdzeniu.',
    protect_credentials: 'Zatrzymaj się i nie podawaj hasła ani kodu',
    protect_credentials_how: 'Nie odpowiadaj hasłem ani kodem. Poproś zaufaną osobę dorosłą o pomoc lub skontaktuj się z pomocą przez znaną Ci oficjalną aplikację albo stronę, otwartą bez linku z wiadomości.',
    verify_payment: 'Sprawdź prośbę, zanim zapłacisz',
    verify_payment_how: 'Skontaktuj się z nadawcą przez wcześniej znany kontakt. Możesz poprosić zaufaną osobę o pomoc, zanim przekażesz pieniądze.',
    verify_prize: 'Sprawdź nagrodę poza wiadomością',
    verify_prize_how: 'Otwórz znaną Ci oficjalną aplikację lub stronę samodzielnie, bez podanego linku. Sprawdź, czy taka nagroda jest tam opisana, lub poproś zaufaną osobę dorosłą o pomoc.',
    pause_and_verify: 'Zatrzymaj się i sprawdź bez pośpiechu',
    pause_and_verify_how: 'Zrób przerwę. Skontaktuj się z nadawcą przez wcześniej znany kontakt albo otwórz znaną Ci oficjalną aplikację bez linku z wiadomości. Możesz poprosić zaufaną osobę dorosłą o pomoc.',
  }),
  submitError: 'Coś poszło nie tak. Odśwież stronę i spróbuj jeszcze raz.',
  howToHeading: 'Jak to działa',
  howToSteps: ['Zaznacz wiadomość, którą chcesz sprawdzić.', 'Kliknij mnie.', 'Sprawdź tekst i odpowiedz na pytania.', 'Jeśli chcesz, pokaż wiadomość opiekunowi.'],
  howToPrivacy: 'Widzę tylko to, co mi pokażesz. Opiekun dostaje tylko to, co sam wyślesz — wynik sprawdzania zostaje u Ciebie.',
});
